### ISSUE TITLE
Changes to Activies/README

### ISSUE THREAD

**Issue by jungshadow** [it-dept-cis/RABET-V-Pilot#49]
Changes to `docs/source/Activities/README.md`:

- [ ] [Graphic: Define why the reporting is conditional](https://github.com/it-dept-cis/RABET-V-Pilot/blob/master/docs/source/Activities/README.md?plain=1#L21)
- [ ] Graphic: Is testing rules determination really conditional? When would you go through an iteration and not determine testing rules?
- [ ] Graphic: Should we change "conditional" to reflect that it could be full, iterative/partial, or not needed?
- [ ] Graphic: Change "Provider Submission" to "RTP Submission"
- [ ] Graphic: Change "Technology Provider Activity" in key to "RTP Activity"

**Comment by wilsoaa** [comment]
@jungshadow sorry for my late reply but I dont have the source for that graphic either. CIS marketing made that graphic and will have the source.

**Comment by katyowenshubler** [comment]
@mike-garcia these are the changes we need to the flow chart graphic once we get that from CIS marketing.
