### ISSUE TITLE
Changes to Security_Claims_Validation

### ISSUE THREAD

**Issue by jungshadow** [it-dept-cis/RABET-V-Pilot#53]
Changes to `docs/source/Activities/Security_Claims_Validation.md`:

- [ ] Consider removing sections detailing how elections work (NB: if there is a need to keep them, explain why they are necessary).

**Comment by jungshadow** [comment]
@mike-garcia I agree this would be great, but it also seems like the content here is generally—not necessarily ideally—fine, as-is. To @JDziurlaj's point, can we push this to the 2022 pilot with the other changes @planglois925 is proposing?

**Comment by mike-garcia** [comment]
I think it's just this: 

`
#### Data Criticality

Different types of data carry different levels of criticality. The following sections review some of the most critical election data elements, identify the typical lifecycle for that data, and discuss the points where its value is the highest.
- Jurisdictional: The jurisdictional data used to assign ballot contents to the correct geographical districts and polling places is most at risk when it is used to build the ballots and assign them. This puts the entire supply chain of that data leading up to ballot generation at risk.
- Voter: While voter data varies between jurisdiction, some--especially non-public voter data--is a target for identity thieves and other criminals.
- Election definition: A combination of jurisdictional information, candidate filing information, and other attributes. Once the election definition is created and approved by the jurisdiction, its integrity has critical value.
- Blank Ballot: The collection of ballot contents into ballot styles. Modification of blank ballots can disenfranchise voters or manipulate how their intent will be read by the voting machine tabulators; they are most at risk from the time they are approved by the election jurisdiction to when they are presented to the voter for marking.
- Election Results: The aggregated totals generated from voting system tabulation functions. 
Election night results are a form of unofficial election results and are at significant risk of tampering and manipulation. The outcome of such tampering would lead to widespread confusion and distrust in the correct result produced by the voting system.

#### Election Operations

This consideration reviews how critical the product, and its services, are to an election’s operations. Is the product a single point of failure? What options are available as backups for election officials? Is the product used during non-peak times or peak times?
`
