### ISSUE TITLE
Changes to SSCM section

### ISSUE THREAD

**Issue by jungshadow** [it-dept-cis/RABET-V-Pilot#57]
SSCM

- [ ] Describe the testing methods before we get into the details of how we test the requirements.
- [ ] Remove references to EIAT as a source (e.g. [here](https://github.com/it-dept-cis/RABET-V-Pilot/blob/master/docs/source/Security_Services_Capability_Maturity_Index/System_Integrity_Requirements.md?plain=1#L221)). If there isn't an appropriate substitute reference, leave it without a reference.

**Comment by katyowenshubler** [comment]
@planglois925 Could you add what Mike requested above on testing methods that existed for that pilot?

**Comment by planglois925** [comment]
@mike-garcia  some quick clarification, when we list the "methods' associated with the requirements this was in reference to how the requirements were created (just a copy of the original requirement, derived or some form of reinterpretation) from the original set of best practices. So it was more or less of a reference field that allows us to tie back to the requirements to some authoritative source in some fashion. Honestly, we might be able to cut it from the report. 

With that said, we do have a page of content that describes the types of tests that we conduct, tho it's not tied to the specific requirements, it just provides a list. I can add that as a PR (and remove the methods) if it's what you're looking for.

**Comment by jungshadow** [comment]
@planglois925 If @mike-garcia doesn't mind me answering for him, that sounds like that should work. A PR would be great (that way we can tweak if needed).

**Comment by mike-garcia** [comment]
Yes, that sounds exactly right and really helps me understand what the heck the copy method of testing is!

**Comment by planglois925** [comment]
I guess I'm missing the right to publish a branch and open a PR. I have the edits queued up once we have that sorted out.

**Comment by jungshadow** [comment]
@planglois925 😢 Well that's a bummer. I imagine @mike-garcia may have to chat with someone to sort out your permissions. As a stopgap, can you fork this repository, make a change in your own GitHub space, and submit a PR from there?

**Comment by planglois925** [comment]
https://github.com/it-dept-cis/RABET-V-Pilot/pull/76
