### ISSUE TITLE
review for accuracy

### ISSUE THREAD

**Issue by katyowenshubler** [it-dept-cis/RABET-V-Pilot#84]
https://github.com/it-dept-cis/RABET-V-Pilot/blob/master/docs/source/Activities/Testing_Rules_Determination.md
Do we use the decision tree as described here? I don't feel like we did use it for the VR Systems 2nd iteration, but that could be because we ended up doing a full review? Please review for accuracy.

**Comment by JDziurlaj** [comment]
The new structure is given by the function `determine_test_rules(change type, SSAM score, SAM score) -> test rules`.
